# execution order of components and modules
# components and modules list below will sorted by execution order
# all other will executed and list as is in vagrant_machine.sh
priorities:
  order:
    - system
    - deps
    - devtools
    - gui
  components:
    system:
      - repo_yandex
      - upgrade
      - user
      - hostname
      - ubuntu_fonts
    deps:
      - curl
      - openssl
      - wget
      - apt_add_repository
    devtools:
      - pip
      - venv
      - rvm