# execution order of components and modules
# components and modules list below will sorted by execution order
# all other will executed and list as is in vagrant_machine.sh
vagrant:
  box: "precise64"
priorities:
  order:
    - system
    - deps
    - gui
    - devtools
    - java
    - web
    - db
    - configs
  components:
    system:
      - repo_yandex
      - upgrade
      - user
      - hostname
    deps:
      - apt_add_repository
    devtools:
      - pip
      - venv
      - rvm